[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:xvfb]
command=/usr/bin/Xvfb :0 -screen 0 1440x900x24
autorestart=true
priority=10

[program:fluxbox]
command=/usr/bin/fluxbox
environment=DISPLAY=":0"
autorestart=true
priority=20

[program:x11vnc]
command=/usr/bin/x11vnc -display :0 -nopw -forever -shared -rfbport 5900
autorestart=true
priority=30

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc/ 8080 localhost:5900
autorestart=true
priority=40

[program:qgc]
command=/opt/qgc/AppRun
user=qgc
environment=DISPLAY=":0",QT_X11_NO_MITSHM="1",HOME="/home/qgc"
autorestart=true
priority=50
